# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee8b7860a02c37287c95aaec3b314136d1eb078c6c8427a6cc3bf567d3d9e6dbfd74729c8bf84b9284b32ddccbab9a109b24f7347fea1baa8f1e8b25e456efda

test:
  secret_key_base: fb60809d74a1e6ae8a9b3f7dbeb19b5abe5018963fe75e380b4f1a7cbfb3b9280524411921d03c0f40783e7d430275566b8a5b7bae10769f2044da0c02e947e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
